### PR TITLE
Fixing issue with DateTime conversion from Cassandra Date, Time, Time…

### LINKED ISSUE #63: \Cassandra\Timeuuid::toDateTime() does not work
Calling this method  results in 
`php: symbol lookup error: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/cassandra.so: undefined symbol: _Z20php_date_get_date_cev`

Code to reproduce:

```php
$uuidCs = new \Cassandra\Timeuuid(time());
$uuidCs->toDateTime();
```

### PR DESCRIPTION
**Pull request by CodeLieutenant**
Fixes #63

### CODE REVIEW

File: src/Date.cpp [hunk 1]
```diff
@@ -14,167 +14,149 @@
...
+  bool isNull = false;
   php_driver_date *self;
 
-  if (zend_parse_parameters(ZEND_NUM_ARGS() , "|z", &seconds) == FAILURE) {
+  ZEND_PARSE_PARAMETERS_START(0, 1)
+  Z_PARAM_OPTIONAL
+  Z_PARAM_LONG_OR_NULL(seconds, isNull)
+  ZEND_PARSE_PARAMETERS_END();
+
+  if (zend_parse_parameters(ZEND_NUM_ARGS(), "|z", &seconds) == FAILURE) {
```
Comment (CodeLieutenant) [inline src/Date.cpp]: BUG! Parsing params twice

File: src/Date.cpp [hunk 2]
```diff
@@ -14,167 +14,149 @@
...
-                                 NULL,
-                                 "gettimestamp",
-                                 &retval);
+  zval getTimeStampResult;
+  zend_call_method_with_0_params(Z_OBJ_P(datetime), php_date_get_date_ce(),
+                                 nullptr, "gettimestamp", &getTimeStampResult);
 
-  if (!PHP5TO7_ZVAL_IS_UNDEF(retval) &&
-      Z_TYPE_P(PHP5TO7_ZVAL_MAYBE_P(retval)) == IS_LONG) {
+  if (!Z_ISUNDEF(getTimeStampResult) &&
```
Comment (CodeLieutenant) [inline src/Date.cpp]: Redundant check

File: src/Date.cpp [hunk 3]
```diff
@@ -188,124 +170,86 @@ ZEND_END_ARG_INFO()
...
-{
+static unsigned php_driver_date_hash_value(zval *obj) {
   php_driver_date *self = PHP_DRIVER_GET_DATE(obj);
   return 31 * 17 + self->date;
 }
 
-static void
-php_driver_date_free(php5to7_zend_object_free *object )
-{
+static void php_driver_date_free(php5to7_zend_object_free *object) {
```
Comment (CodeLieutenant) [inline src/Date.cpp]: looks like a default free handler. can be safely removed

File: src/Time.cpp [hunk 4]
```diff
@@ -19,106 +19,77 @@
...
-void
-php_driver_time_init(INTERNAL_FUNCTION_PARAMETERS)
-{
-  zval *nanoseconds = NULL;
+void php_driver_time_init(INTERNAL_FUNCTION_PARAMETERS) {
+  zval *nanoseconds = nullptr;
   php_driver_time *self;
 
-  if (zend_parse_parameters(ZEND_NUM_ARGS() , "|z", &nanoseconds) == FAILURE) {
+  if (zend_parse_parameters(ZEND_NUM_ARGS(), "|z", &nanoseconds) == FAILURE) {
```
Comment (CodeLieutenant) [inline src/Time.cpp]: replace with ZEND_PARSE_PARAMS macro

File: src/Time.cpp [hunk 5]
```diff
@@ -216,121 +172,85 @@ ZEND_END_ARG_INFO()
...
-{
+static unsigned php_driver_time_hash_value(zval *obj) {
   php_driver_time *self = PHP_DRIVER_GET_TIME(obj);
   return php_driver_bigint_hash(self->time);
 }
 
-static void
-php_driver_time_free(php5to7_zend_object_free *object )
-{
+static void php_driver_time_free(php5to7_zend_object_free *object) {
```
Comment (CodeLieutenant) [inline src/Time.cpp]: same as default handler
